server:
  port: 8081
spring:
  datasource:
    url: ${PG_DB:jdbc:postgresql://localhost:5432/banco}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  h2:
    console:
      enabled: false

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
